# Generated by Django 3.0.6 on 2020-05-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200524_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(default='!Add an item!', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='varient',
            field=models.CharField(default='!Add an varient!', max_length=50),
        ),
    ]
